package main

type Site struct {
	name       string
	errorMsg   string
	checkBy    string
	profileUrl string
	mainUrl    string
	regexCheck string
}

var sites = []Site{
	Site{
		name:       "500px",
		checkBy:    "status_code",
		profileUrl: "https://500px.com/%s",
		mainUrl:    "https://500px.com/",
	},
	Site{
		name:       "9GAG",
		checkBy:    "status_code",
		profileUrl: "https://9gag.com/u/%s",
		mainUrl:    "https://9gag.com/",
	},
	Site{
		name:       "About.me",
		checkBy:    "status_code",
		profileUrl: "https://about.me/%s",
		mainUrl:    "https://about.me/",
	},
	Site{
		name:       "Academia.edu",
		checkBy:    "status_code",
		profileUrl: "https://independent.academia.edu/%s",
		mainUrl:    "https://www.academia.edu/",
	},
	Site{
		name:       "AngelList",
		checkBy:    "status_code",
		profileUrl: "https://angel.co/%s",
		mainUrl:    "https://angel.co/",
	},
	Site{
		name:       "Aptoide",
		checkBy:    "status_code",
		profileUrl: "https://%s.en.aptoide.com/",
		mainUrl:    "https://en.aptoide.com/",
	},
	Site{
		name:       "AskFM",
		checkBy:    "status_code",
		profileUrl: "https://ask.fm/%s",
		mainUrl:    "https://ask.fm/",
	},
	Site{
		name:       "BLIP.fm",
		checkBy:    "status_code",
		profileUrl: "https://blip.fm/%s",
		mainUrl:    "https://blip.fm/",
	},
	Site{
		name:       "Badoo",
		checkBy:    "status_code",
		profileUrl: "https://badoo.com/profile/%s",
		mainUrl:    "https://badoo.com/",
	},
	Site{
		name:       "Bandcamp",
		checkBy:    "status_code",
		profileUrl: "https://www.bandcamp.com/%s",
		mainUrl:    "https://www.bandcamp.com/",
	},
	Site{
		name:       "Basecamp",
		errorMsg:   "The account you were looking for doesn't exist",
		checkBy:    "page_content",
		profileUrl: "https://%s.basecamphq.com",
		mainUrl:    "https://basecamp.com/",
	},
	Site{
		name:       "Behance",
		checkBy:    "status_code",
		profileUrl: "https://www.behance.net/%s",
		mainUrl:    "https://www.behance.net/",
	},
	Site{
		name:       "BitBucket",
		checkBy:    "status_code",
		profileUrl: "https://bitbucket.org/%s/",
		mainUrl:    "https://bitbucket.org/",
	},
	Site{
		name:       "BitCoinForum",
		errorMsg:   "The user whose profile you are trying to view does not exist.",
		checkBy:    "page_content",
		profileUrl: "https://bitcoinforum.com/profile/%s",
		mainUrl:    "https://bitcoinforum.com",
	},
	Site{
		name:       "Blogger",
		checkBy:    "status_code",
		regexCheck: "^[a-zA-Z][a-zA-Z0-9_-]*$",
		profileUrl: "https://%s.blogspot.com",
		mainUrl:    "https://www.blogger.com/",
	},
	Site{
		name:       "BuzzFeed",
		checkBy:    "status_code",
		profileUrl: "https://buzzfeed.com/%s",
		mainUrl:    "https://buzzfeed.com/",
	},
	Site{
		name:       "Canva",
		checkBy:    "status_code",
		profileUrl: "https://www.canva.com/%s",
		mainUrl:    "https://www.canva.com/",
	},
	Site{
		name:       "Carbonmade",
		checkBy:    "response_url",
		profileUrl: "https://%s.carbonmade.com",
		mainUrl:    "https://carbonmade.com/",
	},
	Site{
		name:       "CashMe",
		checkBy:    "status_code",
		profileUrl: "https://cash.me/%s",
		mainUrl:    "https://cash.me/",
	},
	Site{
		name:       "Cloob",
		checkBy:    "status_code",
		profileUrl: "https://www.cloob.com/name/%s",
		mainUrl:    "https://www.cloob.com/",
	},
	Site{
		name:       "Codecademy",
		checkBy:    "status_code",
		profileUrl: "https://www.codecademy.com/%s",
		mainUrl:    "https://www.codecademy.com/",
	},
	Site{
		name:       "Codementor",
		checkBy:    "status_code",
		profileUrl: "https://www.codementor.io/%s",
		mainUrl:    "https://www.codementor.io/",
	},
	Site{
		name:       "Codepen",
		checkBy:    "status_code",
		profileUrl: "https://codepen.io/%s",
		mainUrl:    "https://codepen.io/",
	},
	Site{
		name:       "Coderwall",
		errorMsg:   "404! Our feels when that url is used",
		checkBy:    "page_content",
		profileUrl: "https://coderwall.com/%s",
		mainUrl:    "https://coderwall.com/",
	},
	Site{
		name:       "ColourLovers",
		checkBy:    "status_code",
		profileUrl: "https://www.colourlovers.com/lover/%s",
		mainUrl:    "https://www.colourlovers.com/",
	},
	Site{
		name:       "Contently",
		errorMsg:   "We can't find that page!",
		checkBy:    "page_content",
		regexCheck: "^[a-zA-Z][a-zA-Z0-9_-]*$",
		profileUrl: "https://%s.contently.com/",
		mainUrl:    "https://contently.com/",
	},
	Site{
		name:       "Coroflot",
		checkBy:    "status_code",
		profileUrl: "https://www.coroflot.com/%s",
		mainUrl:    "https://coroflot.com/",
	},
	Site{
		name:       "CreativeMarket",
		checkBy:    "status_code",
		profileUrl: "https://creativemarket.com/%s",
		mainUrl:    "https://creativemarket.com/",
	},
	Site{
		name:       "Crevado",
		checkBy:    "status_code",
		profileUrl: "https://%s.crevado.com",
		mainUrl:    "https://crevado.com/",
	},
	Site{
		name:       "Crunchyroll",
		checkBy:    "status_code",
		profileUrl: "https://www.crunchyroll.com/user/%s",
		mainUrl:    "https://www.crunchyroll.com/",
	},
	Site{
		name:       "DEV Community",
		checkBy:    "status_code",
		regexCheck: "^[a-zA-Z][a-zA-Z0-9_-]*$",
		profileUrl: "https://dev.to/%s",
		mainUrl:    "https://dev.to/",
	},
	Site{
		name:       "DailyMotion",
		checkBy:    "status_code",
		profileUrl: "https://www.dailymotion.com/%s",
		mainUrl:    "https://www.dailymotion.com/",
	},
	Site{
		name:       "Designspiration",
		checkBy:    "status_code",
		profileUrl: "https://www.designspiration.net/%s/",
		mainUrl:    "https://www.designspiration.net/",
	},
	Site{
		name:       "DeviantART",
		checkBy:    "status_code",
		regexCheck: "^[a-zA-Z][a-zA-Z0-9_-]*$",
		profileUrl: "https://%s.deviantart.com",
		mainUrl:    "https://deviantart.com",
	},
	Site{
		name:       "Discogs",
		checkBy:    "status_code",
		profileUrl: "https://www.discogs.com/user/%s",
		mainUrl:    "https://www.discogs.com/",
	},
	Site{
		name:       "Disqus",
		checkBy:    "status_code",
		profileUrl: "https://disqus.com/%s",
		mainUrl:    "https://disqus.com/",
	},
	Site{
		name:       "Docker Hub",
		checkBy:    "status_code",
		profileUrl: "https://hub.docker.com/u/%s/",
		mainUrl:    "https://hub.docker.com/",
	},
	Site{
		name:       "Dribbble",
		errorMsg:   "Whoops, that page is gone.",
		checkBy:    "page_content",
		regexCheck: "^[a-zA-Z][a-zA-Z0-9_-]*$",
		profileUrl: "https://dribbble.com/%s",
		mainUrl:    "https://dribbble.com/",
	},
	Site{
		name:       "EVE Online",
		checkBy:    "status_code",
		profileUrl: "https://evewho.com/pilot/%s/",
		mainUrl:    "https://eveonline.com",
	},
	Site{
		name:       "Ebay",
		errorMsg:   "The User ID you entered was not found",
		checkBy:    "page_content",
		profileUrl: "https://www.ebay.com/usr/%s",
		mainUrl:    "https://www.ebay.com/",
	},
	Site{
		name:       "Ello",
		errorMsg:   "We couldn't find the page you're looking for",
		checkBy:    "page_content",
		profileUrl: "https://ello.co/%s",
		mainUrl:    "https://ello.co/",
	},
	Site{
		name:       "Etsy",
		checkBy:    "status_code",
		profileUrl: "https://www.etsy.com/shop/%s",
		mainUrl:    "https://www.etsy.com/",
	},
	Site{
		name:       "EyeEm",
		checkBy:    "response_url",
		profileUrl: "https://www.eyeem.com/u/%s",
		mainUrl:    "https://www.eyeem.com/",
	},
	Site{
		name:       "Facebook",
		checkBy:    "status_code",
		regexCheck: "^[a-zA-Z0-9]{4,49}(?<!.com|.org|.net)$",
		profileUrl: "https://www.facebook.com/%s",
		mainUrl:    "https://www.facebook.com/",
	},
	Site{
		name:       "Fandom",
		checkBy:    "status_code",
		profileUrl: "https://www.fandom.com/u/%s",
		mainUrl:    "https://www.fandom.com/",
	},
	Site{
		name:       "Flickr",
		checkBy:    "status_code",
		profileUrl: "https://www.flickr.com/people/%s",
		mainUrl:    "https://www.flickr.com/",
	},
	Site{
		name:       "Flipboard",
		checkBy:    "status_code",
		regexCheck: "^([a-zA-Z0-9_]){1,15}$",
		profileUrl: "https://flipboard.com/@%s",
		mainUrl:    "https://flipboard.com/",
	},
	Site{
		name:       "Foursquare",
		checkBy:    "status_code",
		profileUrl: "https://foursquare.com/%s",
		mainUrl:    "https://foursquare.com/",
	},
	Site{
		name:       "Giphy",
		checkBy:    "status_code",
		profileUrl: "https://giphy.com/%s",
		mainUrl:    "https://giphy.com/",
	},
	Site{
		name:       "GitHub",
		checkBy:    "status_code",
		regexCheck: "^[a-zA-Z0-9](?:[a-zA-Z0-9]|-(?=[a-zA-Z0-9])){0,38}$",
		profileUrl: "https://www.github.com/%s",
		mainUrl:    "https://www.github.com/",
	},
	Site{
		name:       "GitLab",
		errorMsg:   "You need to sign in or sign up before continuing.",
		checkBy:    "page_content",
		profileUrl: "https://gitlab.com/%s",
		mainUrl:    "https://gitlab.com/",
	},
	Site{
		name:       "Gitee",
		checkBy:    "status_code",
		profileUrl: "https://gitee.com/%s",
		mainUrl:    "https://gitee.com/",
	},
	Site{
		name:       "GoodReads",
		checkBy:    "status_code",
		profileUrl: "https://www.goodreads.com/%s",
		mainUrl:    "https://www.goodreads.com/",
	},
	Site{
		name:       "Gravatar",
		checkBy:    "status_code",
		profileUrl: "http://en.gravatar.com/%s",
		mainUrl:    "http://en.gravatar.com/",
	},
	Site{
		name:       "Gumroad",
		errorMsg:   "Page not found.",
		checkBy:    "page_content",
		profileUrl: "https://www.gumroad.com/%s",
		mainUrl:    "https://www.gumroad.com/",
	},
	Site{
		name:       "HackerNews",
		errorMsg:   "No such user.",
		checkBy:    "page_content",
		profileUrl: "https://news.ycombinator.com/user?id=%s",
		mainUrl:    "https://news.ycombinator.com/",
	},
	Site{
		name:       "HackerOne",
		errorMsg:   "Page not found",
		checkBy:    "page_content",
		profileUrl: "https://hackerone.com/%s",
		mainUrl:    "https://hackerone.com/",
	},
	Site{
		name:       "House-Mixes.com",
		errorMsg:   "Profile Not Found",
		checkBy:    "page_content",
		profileUrl: "https://www.house-mixes.com/profile/%s",
		mainUrl:    "https://www.house-mixes.com/",
	},
	Site{
		name:       "Houzz",
		errorMsg:   "The page you requested was not found.",
		checkBy:    "page_content",
		profileUrl: "https://houzz.com/user/%s",
		mainUrl:    "https://houzz.com/",
	},
	Site{
		name:       "HubPages",
		checkBy:    "status_code",
		profileUrl: "https://hubpages.com/@%s",
		mainUrl:    "https://hubpages.com/",
	},
	Site{
		name:       "IFTTT",
		errorMsg:   "The requested page or file does not exist",
		checkBy:    "page_content",
		profileUrl: "https://www.ifttt.com/p/%s",
		mainUrl:    "https://www.ifttt.com/",
	},
	Site{
		name:       "ImageShack",
		checkBy:    "response_url",
		profileUrl: "https://imageshack.us/user/%s",
		mainUrl:    "https://imageshack.us/",
	},
	Site{
		name:       "Imgur",
		checkBy:    "status_code",
		profileUrl: "https://imgur.com/user/%s",
		mainUrl:    "https://imgur.com/",
	},
	Site{
		name:       "Instagram",
		errorMsg:   "The link you followed may be broken",
		checkBy:    "page_content",
		profileUrl: "https://www.instagram.com/%s",
		mainUrl:    "https://www.instagram.com/",
	},
	Site{
		name:       "Instructables",
		errorMsg:   "404: We're sorry, things break sometimes",
		checkBy:    "page_content",
		profileUrl: "https://www.instructables.com/member/%s",
		mainUrl:    "https://www.instructables.com/",
	},
	Site{
		name:       "Investing.com",
		checkBy:    "status_code",
		profileUrl: "https://www.investing.com/traders/%s",
		mainUrl:    "https://www.investing.com/",
	},
	Site{
		name:       "Issuu",
		checkBy:    "status_code",
		profileUrl: "https://issuu.com/%s",
		mainUrl:    "https://issuu.com/",
	},
	Site{
		name:       "Itch.io",
		checkBy:    "status_code",
		profileUrl: "https://%s.itch.io/",
		mainUrl:    "https://itch.io/",
	},
	Site{
		name:       "Jimdo",
		checkBy:    "status_code",
		profileUrl: "https://%s.jimdosite.com",
		mainUrl:    "https://jimdosite.com/",
	},
	Site{
		name:       "Kaggle",
		checkBy:    "status_code",
		profileUrl: "https://www.kaggle.com/%s",
		mainUrl:    "https://www.kaggle.com/",
	},
	Site{
		name:       "KanoWorld",
		checkBy:    "status_code",
		profileUrl: "https://api.kano.me/progress/user/%s",
		mainUrl:    "https://world.kano.me/",
	},
	Site{
		name:       "Keybase",
		checkBy:    "status_code",
		profileUrl: "https://keybase.io/%s",
		mainUrl:    "https://keybase.io/",
	},
	Site{
		name:       "Kik",
		errorMsg:   "The page you requested was not found",
		checkBy:    "page_content",
		profileUrl: "https://ws2.kik.com/user/%s",
		mainUrl:    "http://kik.me/",
	},
	Site{
		name:       "Kongregate",
		errorMsg:   "Sorry, no account with that name was found.",
		checkBy:    "page_content",
		regexCheck: "^[a-zA-Z][a-zA-Z0-9_-]*$",
		profileUrl: "https://www.kongregate.com/accounts/%s",
		mainUrl:    "https://www.kongregate.com/",
	},
	Site{
		name:       "Launchpad",
		checkBy:    "status_code",
		profileUrl: "https://launchpad.net/~%s",
		mainUrl:    "https://launchpad.net/",
	},
	Site{
		name:       "Letterboxd",
		errorMsg:   "Sorry, we can\u2019t find the page you\u2019ve requested.",
		checkBy:    "page_content",
		profileUrl: "https://letterboxd.com/%s",
		mainUrl:    "https://letterboxd.com/",
	},
	Site{
		name:       "LiveJournal",
		checkBy:    "status_code",
		regexCheck: "^[a-zA-Z][a-zA-Z0-9_-]*$",
		profileUrl: "https://%s.livejournal.com",
		mainUrl:    "https://www.livejournal.com/",
	},
	Site{
		name:       "Mastodon",
		checkBy:    "status_code",
		profileUrl: "https://mstdn.io/@%s",
		mainUrl:    "https://mstdn.io/",
	},
	Site{
		name:       "Medium",
		checkBy:    "status_code",
		profileUrl: "https://medium.com/@%s",
		mainUrl:    "https://medium.com/",
	},
	Site{
		name:       "MeetMe",
		checkBy:    "response_url",
		profileUrl: "https://www.meetme.com/%s",
		mainUrl:    "https://www.meetme.com/",
	},
	Site{
		name:       "MixCloud",
		errorMsg:   "Page Not Found",
		checkBy:    "page_content",
		profileUrl: "https://www.mixcloud.com/%s",
		mainUrl:    "https://www.mixcloud.com/",
	},
	Site{
		name:       "MyAnimeList",
		checkBy:    "status_code",
		profileUrl: "https://myanimelist.net/profile/%s",
		mainUrl:    "https://myanimelist.net/",
	},
	Site{
		name:       "Myspace",
		checkBy:    "status_code",
		profileUrl: "https://myspace.com/%s",
		mainUrl:    "https://myspace.com/",
	},
	Site{
		name:       "NameMC (Minecraft.net skins)",
		errorMsg:   "Profiles: 0 results",
		checkBy:    "page_content",
		profileUrl: "https://namemc.com/profile/%s",
		mainUrl:    "https://namemc.com/",
	},
	Site{
		name:       "Newgrounds",
		checkBy:    "status_code",
		regexCheck: "^[a-zA-Z][a-zA-Z0-9_-]*$",
		profileUrl: "https://%s.newgrounds.com",
		mainUrl:    "https://newgrounds.com",
	},
	Site{
		name:       "Pastebin",
		checkBy:    "response_url",
		profileUrl: "https://pastebin.com/u/%s",
		mainUrl:    "https://pastebin.com/",
	},
	Site{
		name:       "Patreon",
		checkBy:    "status_code",
		profileUrl: "https://www.patreon.com/%s",
		mainUrl:    "https://www.patreon.com/",
	},
	Site{
		name:       "Pexels",
		errorMsg:   "Ouch, something went wrong!",
		checkBy:    "page_content",
		profileUrl: "https://www.pexels.com/@%s",
		mainUrl:    "https://www.pexels.com/",
	},
	Site{
		name:       "Photobucket",
		checkBy:    "status_code",
		profileUrl: "https://photobucket.com/user/%s/library",
		mainUrl:    "https://photobucket.com/",
	},
	Site{
		name:       "Pinterest",
		checkBy:    "response_url",
		profileUrl: "https://www.pinterest.com/%s/",
		mainUrl:    "https://www.pinterest.com/",
	},
	Site{
		name:       "Pixabay",
		checkBy:    "status_code",
		profileUrl: "https://pixabay.com/en/users/%s",
		mainUrl:    "https://pixabay.com/",
	},
	Site{
		name:       "Plug.DJ",
		checkBy:    "status_code",
		profileUrl: "https://plug.dj/@/%s",
		mainUrl:    "https://plug.dj/",
	},
	Site{
		name:       "Pokemon Showdown",
		checkBy:    "status_code",
		profileUrl: "https://pokemonshowdown.com/users/%s",
		mainUrl:    "https://pokemonshowdown.com",
	},
	Site{
		name:       "ProductHunt",
		errorMsg:   "Product Hunt is a curation of the best new products",
		checkBy:    "page_content",
		profileUrl: "https://www.producthunt.com/@%s",
		mainUrl:    "https://www.producthunt.com/",
	},
	Site{
		name:       "Quora",
		checkBy:    "response_url",
		profileUrl: "https://www.quora.com/profile/%s",
		mainUrl:    "https://www.quora.com/",
	},
	Site{
		name:       "Rajce.net",
		errorMsg:   "410",
		checkBy:    "page_content",
		profileUrl: "https://%s.rajce.idnes.cz/",
		mainUrl:    "https://www.rajce.idnes.cz/",
	},
	Site{
		name:       "Rate Your Music",
		checkBy:    "status_code",
		profileUrl: "https://rateyourmusic.com/~%s",
		mainUrl:    "https://rateyourmusic.com/",
	},
	Site{
		name:       "Reddit",
		checkBy:    "status_code",
		profileUrl: "https://www.reddit.com/user/%s",
		mainUrl:    "https://www.reddit.com/",
	},
	Site{
		name:       "Repl.it",
		errorMsg:   "404",
		checkBy:    "page_content",
		profileUrl: "https://repl.it/@%s",
		mainUrl:    "https://repl.it/",
	},
	Site{
		name:       "ResearchGate",
		checkBy:    "response_url",
		regexCheck: "\\w+_\\w+",
		profileUrl: "https://www.researchgate.net/profile/%s",
		mainUrl:    "https://www.researchgate.net/",
	},
	Site{
		name:       "ReverbNation",
		errorMsg:   "Sorry, we couldn't find that page",
		checkBy:    "page_content",
		profileUrl: "https://www.reverbnation.com/%s",
		mainUrl:    "https://www.reverbnation.com/",
	},
	Site{
		name:       "Roblox",
		errorMsg:   "Page cannot be found or no longer exists",
		checkBy:    "page_content",
		profileUrl: "https://www.roblox.com/user.aspx?username=%s",
		mainUrl:    "https://www.roblox.com/",
	},
	Site{
		name:       "Scribd",
		errorMsg:   "Page not found",
		checkBy:    "page_content",
		profileUrl: "https://www.scribd.com/%s",
		mainUrl:    "https://www.scribd.com/",
	},
	Site{
		name:       "Signal",
		errorMsg:   "Oops! That page doesn\u2019t exist or is private.",
		checkBy:    "page_content",
		profileUrl: "https://community.signalusers.org/u/%s",
		mainUrl:    "https://community.signalusers.org",
	},
	Site{
		name:       "Slack",
		checkBy:    "status_code",
		regexCheck: "^[a-zA-Z][a-zA-Z0-9_-]*$",
		profileUrl: "https://%s.slack.com",
		mainUrl:    "https://slack.com",
	},
	Site{
		name:       "SlideShare",
		checkBy:    "status_code",
		profileUrl: "https://slideshare.net/%s",
		mainUrl:    "https://slideshare.net/",
	},
	Site{
		name:       "Smashcast",
		checkBy:    "status_code",
		profileUrl: "https://www.smashcast.tv/api/media/live/%s",
		mainUrl:    "https://www.smashcast.tv/",
	},
	Site{
		name:       "SoundCloud",
		checkBy:    "status_code",
		profileUrl: "https://soundcloud.com/%s",
		mainUrl:    "https://soundcloud.com/",
	},
	Site{
		name:       "SourceForge",
		checkBy:    "status_code",
		profileUrl: "https://sourceforge.net/u/%s",
		mainUrl:    "https://sourceforge.net/",
	},
	Site{
		name:       "Spotify",
		checkBy:    "status_code",
		profileUrl: "https://open.spotify.com/user/%s",
		mainUrl:    "https://open.spotify.com/",
	},
	Site{
		name:       "Star Citizen",
		checkBy:    "status_code",
		profileUrl: "https://robertsspaceindustries.com/citizens/%s",
		mainUrl:    "https://robertsspaceindustries.com/",
	},
	Site{
		name:       "Steam",
		errorMsg:   "The specified profile could not be found",
		checkBy:    "page_content",
		profileUrl: "https://steamcommunity.com/id/%s",
		mainUrl:    "https://steamcommunity.com/",
	},
	Site{
		name:       "SteamGroup",
		errorMsg:   "No group could be retrieved for the given URL",
		checkBy:    "page_content",
		profileUrl: "https://steamcommunity.com/groups/%s",
		mainUrl:    "https://steamcommunity.com/",
	},
	Site{
		name:       "Taringa",
		checkBy:    "status_code",
		profileUrl: "https://www.taringa.net/%s",
		mainUrl:    "https://taringa.net/",
	},
	Site{
		name:       "Telegram",
		errorMsg:   "<meta property=\"twitter:title\" content=\"Telegram: Contact",
		checkBy:    "page_content",
		profileUrl: "https://t.me/%s",
		mainUrl:    "https://t.me/",
	},
	Site{
		name:       "Tinder",
		errorMsg:   "Looking for Someone?",
		checkBy:    "page_content",
		profileUrl: "https://www.gotinder.com/@%s",
		mainUrl:    "https://tinder.com/",
	},
	Site{
		name:       "TradingView",
		checkBy:    "status_code",
		profileUrl: "https://www.tradingview.com/u/%s/",
		mainUrl:    "https://www.tradingview.com/",
	},
	Site{
		name:       "Trakt",
		checkBy:    "status_code",
		profileUrl: "https://www.trakt.tv/users/%s",
		mainUrl:    "https://www.trakt.tv/",
	},
	Site{
		name:       "Trip",
		errorMsg:   "Page not found",
		checkBy:    "page_content",
		profileUrl: "https://www.trip.skyscanner.com/user/%s",
		mainUrl:    "https://www.trip.skyscanner.com/",
	},
	Site{
		name:       "TripAdvisor",
		errorMsg:   "This page is on vacation\u2026",
		checkBy:    "page_content",
		profileUrl: "https://tripadvisor.com/members/%s",
		mainUrl:    "https://tripadvisor.com/",
	},
	Site{
		name:       "Twitch",
		checkBy:    "status_code",
		profileUrl: "https://m.twitch.tv/%s",
		mainUrl:    "https://www.twitch.tv/",
	},
	Site{
		name:       "Twitter",
		errorMsg:   "page doesn\u2019t exist",
		checkBy:    "page_content",
		profileUrl: "https://www.twitter.com/%s",
		mainUrl:    "https://www.twitter.com/",
	},
	Site{
		name:       "Unsplash",
		checkBy:    "status_code",
		profileUrl: "https://unsplash.com/@%s",
		mainUrl:    "https://unsplash.com/",
	},
	Site{
		name:       "VK",
		checkBy:    "response_url",
		profileUrl: "https://vk.com/%s",
		mainUrl:    "https://vk.com/",
	},
	Site{
		name:       "VSCO",
		checkBy:    "status_code",
		profileUrl: "https://vsco.co/%s",
		mainUrl:    "https://vsco.co/",
	},
	Site{
		name:       "Venmo",
		checkBy:    "status_code",
		profileUrl: "https://venmo.com/%s",
		mainUrl:    "https://venmo.com/",
	},
	Site{
		name:       "Vimeo",
		checkBy:    "status_code",
		profileUrl: "https://vimeo.com/%s",
		mainUrl:    "https://vimeo.com/",
	},
	Site{
		name:       "VirusTotal",
		errorMsg:   "not found",
		checkBy:    "page_content",
		profileUrl: "https://www.virustotal.com/ui/users/%s/trusted_users",
		mainUrl:    "https://www.virustotal.com/",
	},
	Site{
		name:       "Wattpad",
		errorMsg:   "This page seems to be missing...",
		checkBy:    "page_content",
		profileUrl: "https://www.wattpad.com/user/%s",
		mainUrl:    "https://www.wattpad.com/",
	},
	Site{
		name:       "We Heart It",
		errorMsg:   "Oops! You've landed on a moving target!",
		checkBy:    "page_content",
		profileUrl: "https://weheartit.com/%s",
		mainUrl:    "https://weheartit.com/",
	},
	Site{
		name:       "WebNode",
		checkBy:    "status_code",
		profileUrl: "https://%s.webnode.cz/",
		mainUrl:    "https://www.webnode.cz/",
	},
	Site{
		name:       "Wikipedia",
		errorMsg:   "If a page was recently created here, it may not be visible yet because of a delay in updating the database",
		checkBy:    "page_content",
		profileUrl: "https://www.wikipedia.org/wiki/User:%s",
		mainUrl:    "https://www.wikipedia.org/",
	},
	Site{
		name:       "Wix",
		checkBy:    "status_code",
		profileUrl: "https://%s.wix.com",
		mainUrl:    "https://wix.com/",
	},
	Site{
		name:       "WordPress",
		checkBy:    "response_url",
		regexCheck: "^[a-zA-Z][a-zA-Z0-9_-]*$",
		profileUrl: "https://%s.wordpress.com/",
		mainUrl:    "https://wordpress.com",
	},
	Site{
		name:       "YouNow",
		errorMsg:   "No users found",
		checkBy:    "page_content",
		profileUrl: "https://www.younow.com/%s/",
		mainUrl:    "https://www.younow.com/",
	},
	Site{
		name:       "YouPic",
		checkBy:    "status_code",
		profileUrl: "https://youpic.com/photographer/%s/",
		mainUrl:    "https://youpic.com/",
	},
	Site{
		name:       "YouTube",
		errorMsg:   "Not Found",
		checkBy:    "page_content",
		profileUrl: "https://www.youtube.com/%s",
		mainUrl:    "https://www.youtube.com/",
	},
	Site{
		name:       "Zhihu",
		checkBy:    "response_url",
		profileUrl: "https://www.zhihu.com/people/%s",
		mainUrl:    "https://www.zhihu.com/",
	},
	Site{
		name:       "boingboing.net",
		checkBy:    "status_code",
		profileUrl: "https://bbs.boingboing.net/u/%s",
		mainUrl:    "https://boingboing.net/",
	},
	Site{
		name:       "devRant",
		checkBy:    "response_url",
		profileUrl: "https://devrant.com/users/%s",
		mainUrl:    "https://devrant.com/",
	},
	Site{
		name:       "gfycat",
		checkBy:    "status_code",
		profileUrl: "https://gfycat.com/@%s",
		mainUrl:    "https://gfycat.com/",
	},
	Site{
		name:       "iMGSRC.RU",
		checkBy:    "response_url",
		profileUrl: "https://imgsrc.ru/main/user.php?user=%s",
		mainUrl:    "https://imgsrc.ru/",
	},
	Site{
		name:       "last.fm",
		checkBy:    "status_code",
		profileUrl: "https://last.fm/user/%s",
		mainUrl:    "https://last.fm/",
	},
	Site{
		name:       "osu!",
		checkBy:    "status_code",
		profileUrl: "https://osu.ppy.sh/users/%s",
		mainUrl:    "https://osu.ppy.sh/",
	},
}
